<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTlwscct\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTlwscct/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTlwscct.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTlwscct\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerTlwscct\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Tlwscct',
    'container.build_id' => 'f3e5d2ec',
    'container.build_time' => 1543973838,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTlwscct');
