<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPtgdxn5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPtgdxn5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPtgdxn5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPtgdxn5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPtgdxn5\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ptgdxn5',
    'container.build_id' => '56e4e6cd',
    'container.build_time' => 1559214687,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPtgdxn5');
