<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.cache.config_warmer' shared service.

return $this->services['easyadmin.cache.config_warmer'] = new \EasyCorp\Bundle\EasyAdminBundle\Cache\ConfigWarmer(${($_ = isset($this->services['easyadmin.config.manager']) ? $this->services['easyadmin.config.manager'] : $this->getEasyadmin_Config_ManagerService()) && false ?: '_'});
