<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formacion extends \AppBundle\Entity\Formacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'titulo', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'familiaprof', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'subfamiliaprof', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'creditos', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'extinto', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'level'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'titulo', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'familiaprof', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'subfamiliaprof', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'creditos', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'extinto', '' . "\0" . 'AppBundle\\Entity\\Formacion' . "\0" . 'level'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFamiliaprof($familiaprof)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFamiliaprof', [$familiaprof]);

        return parent::setFamiliaprof($familiaprof);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamiliaprof()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamiliaprof', []);

        return parent::getFamiliaprof();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubfamiliaprof($subfamiliaprof)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubfamiliaprof', [$subfamiliaprof]);

        return parent::setSubfamiliaprof($subfamiliaprof);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubfamiliaprof()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubfamiliaprof', []);

        return parent::getSubfamiliaprof();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditos($creditos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditos', [$creditos]);

        return parent::setCreditos($creditos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditos', []);

        return parent::getCreditos();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacreacion($fechacreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacreacion', [$fechacreacion]);

        return parent::setFechacreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacreacion', []);

        return parent::getFechacreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaborrado($fechaborrado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaborrado', [$fechaborrado]);

        return parent::setFechaborrado($fechaborrado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaborrado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaborrado', []);

        return parent::getFechaborrado();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtinto($extinto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtinto', [$extinto]);

        return parent::setExtinto($extinto);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtinto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtinto', []);

        return parent::getExtinto();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel(\AppBundle\Entity\EducationLevel $level = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', [$level]);

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
