<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Perfilestudiante extends \AppBundle\Entity\Perfilestudiante implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'dni', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'cp', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'localidad', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'pais', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'diponibilidad', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'intereses', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'cvpdf', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'cvtxt', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'sectorprofesional', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'fexibilidadgeografica', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'fechanacimiento', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'telefonouno', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'telefonodos', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'public'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'dni', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'cp', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'localidad', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'pais', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'diponibilidad', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'intereses', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'cvpdf', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'cvtxt', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'sectorprofesional', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'fexibilidadgeografica', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'fechanacimiento', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'telefonouno', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'telefonodos', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Perfilestudiante' . "\0" . 'public'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Perfilestudiante $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDni($dni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDni', [$dni]);

        return parent::setDni($dni);
    }

    /**
     * {@inheritDoc}
     */
    public function getDni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDni', []);

        return parent::getDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$cp]);

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad($localidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiponibilidad($diponibilidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiponibilidad', [$diponibilidad]);

        return parent::setDiponibilidad($diponibilidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiponibilidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiponibilidad', []);

        return parent::getDiponibilidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntereses($intereses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntereses', [$intereses]);

        return parent::setIntereses($intereses);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntereses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntereses', []);

        return parent::getIntereses();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvpdf($cvpdf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvpdf', [$cvpdf]);

        return parent::setCvpdf($cvpdf);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvpdf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvpdf', []);

        return parent::getCvpdf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvtxt($cvtxt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvtxt', [$cvtxt]);

        return parent::setCvtxt($cvtxt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvtxt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvtxt', []);

        return parent::getCvtxt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectorprofesional($sectorprofesional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectorprofesional', [$sectorprofesional]);

        return parent::setSectorprofesional($sectorprofesional);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectorprofesional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectorprofesional', []);

        return parent::getSectorprofesional();
    }

    /**
     * {@inheritDoc}
     */
    public function setFexibilidadgeografica($fexibilidadgeografica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFexibilidadgeografica', [$fexibilidadgeografica]);

        return parent::setFexibilidadgeografica($fexibilidadgeografica);
    }

    /**
     * {@inheritDoc}
     */
    public function getFexibilidadgeografica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFexibilidadgeografica', []);

        return parent::getFexibilidadgeografica();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechanacimiento($fechanacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechanacimiento', [$fechanacimiento]);

        return parent::setFechanacimiento($fechanacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechanacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechanacimiento', []);

        return parent::getFechanacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\AppBundle\Entity\Usuarios $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', [$apellidos]);

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', []);

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonouno($telefonouno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonouno', [$telefonouno]);

        return parent::setTelefonouno($telefonouno);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonouno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonouno', []);

        return parent::getTelefonouno();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonodos($telefonodos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonodos', [$telefonodos]);

        return parent::setTelefonodos($telefonodos);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonodos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonodos', []);

        return parent::getTelefonodos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublic($public)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublic', [$public]);

        return parent::setPublic($public);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublic', []);

        return parent::getPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
