<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \AppBundle\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'plainPassword', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'role', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'username', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'nif', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'done', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'securitytoken'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'plainPassword', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'role', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'username', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'nif', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'done', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'securitytoken'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsernameLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameLogin', []);

        return parent::getUsernameLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', []);

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', [$password]);

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacreacion($fechacreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacreacion', [$fechacreacion]);

        return parent::setFechacreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacreacion', []);

        return parent::getFechacreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaborrado($fechaborrado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaborrado', [$fechaborrado]);

        return parent::setFechaborrado($fechaborrado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaborrado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaborrado', []);

        return parent::getFechaborrado();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDone($done)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDone', [$done]);

        return parent::setDone($done);
    }

    /**
     * {@inheritDoc}
     */
    public function getDone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDone', []);

        return parent::getDone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNif($nif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNif', [$nif]);

        return parent::setNif($nif);
    }

    /**
     * {@inheritDoc}
     */
    public function getNif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNif', []);

        return parent::getNif();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecuritytoken($securitytoken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecuritytoken', [$securitytoken]);

        return parent::setSecuritytoken($securitytoken);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecuritytoken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecuritytoken', []);

        return parent::getSecuritytoken();
    }

}
