<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categorias extends \AppBundle\Entity\Categorias implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'idpadre', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'centroestudios', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'ofertas', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'ofertasid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'idpadre', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'centroestudios', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'ofertas', '' . "\0" . 'AppBundle\\Entity\\Categorias' . "\0" . 'ofertasid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categorias $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpadre($idpadre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpadre', [$idpadre]);

        return parent::setIdpadre($idpadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpadre', []);

        return parent::getIdpadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function addCentroestudio(\AppBundle\Entity\Centroestudios $centroestudio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCentroestudio', [$centroestudio]);

        return parent::addCentroestudio($centroestudio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCentroestudio(\AppBundle\Entity\Centroestudios $centroestudio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCentroestudio', [$centroestudio]);

        return parent::removeCentroestudio($centroestudio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentroestudios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentroestudios', []);

        return parent::getCentroestudios();
    }

    /**
     * {@inheritDoc}
     */
    public function addOferta(\AppBundle\Entity\Ofertas $oferta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOferta', [$oferta]);

        return parent::addOferta($oferta);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOferta(\AppBundle\Entity\Ofertas $oferta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOferta', [$oferta]);

        return parent::removeOferta($oferta);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfertas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfertas', []);

        return parent::getOfertas();
    }

    /**
     * {@inheritDoc}
     */
    public function addOfertasid(\AppBundle\Entity\Ofertas $ofertasid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfertasid', [$ofertasid]);

        return parent::addOfertasid($ofertasid);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOfertasid(\AppBundle\Entity\Ofertas $ofertasid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOfertasid', [$ofertasid]);

        return parent::removeOfertasid($ofertasid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfertasid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfertasid', []);

        return parent::getOfertasid();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
