<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ofertas extends \AppBundle\Entity\Ofertas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fecharevision', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fechainicio', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fechafin', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'vacantes', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'idempresa', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'categoria', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'inscribed', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'vacancies', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'validated', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'active', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'finished', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'closurereason', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'closureexplanation', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'engagement'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fecharevision', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fechainicio', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'fechafin', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'vacantes', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'idempresa', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'categoria', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'inscribed', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'vacancies', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'validated', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'active', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'finished', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'closurereason', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'closureexplanation', '' . "\0" . 'AppBundle\\Entity\\Ofertas' . "\0" . 'engagement'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ofertas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacreacion($fechacreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacreacion', [$fechacreacion]);

        return parent::setFechacreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacreacion', []);

        return parent::getFechacreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharevision($fecharevision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharevision', [$fecharevision]);

        return parent::setFecharevision($fecharevision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharevision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharevision', []);

        return parent::getFecharevision();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaborrado($fechaborrado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaborrado', [$fechaborrado]);

        return parent::setFechaborrado($fechaborrado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaborrado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaborrado', []);

        return parent::getFechaborrado();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', [$fechainicio]);

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', []);

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafin($fechafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafin', [$fechafin]);

        return parent::setFechafin($fechafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafin', []);

        return parent::getFechafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setVacantes($vacantes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVacantes', [$vacantes]);

        return parent::setVacantes($vacantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getVacantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVacantes', []);

        return parent::getVacantes();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdempresa(\AppBundle\Entity\Perfilempresa $idempresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdempresa', [$idempresa]);

        return parent::setIdempresa($idempresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdempresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdempresa', []);

        return parent::getIdempresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(\AppBundle\Entity\Tiposoferta $tipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\AppBundle\Entity\Categorias $categoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidated($validated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidated', [$validated]);

        return parent::setValidated($validated);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidated', []);

        return parent::getValidated();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscribed($inscribed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscribed', [$inscribed]);

        return parent::setInscribed($inscribed);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscribed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscribed', []);

        return parent::getInscribed();
    }

    /**
     * {@inheritDoc}
     */
    public function setVacancies($vacancies)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVacancies', [$vacancies]);

        return parent::setVacancies($vacancies);
    }

    /**
     * {@inheritDoc}
     */
    public function getVacancies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVacancies', []);

        return parent::getVacancies();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinished($finished)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinished', [$finished]);

        return parent::setFinished($finished);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinished', []);

        return parent::getFinished();
    }

    /**
     * {@inheritDoc}
     */
    public function setClosurereason($closurereason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClosurereason', [$closurereason]);

        return parent::setClosurereason($closurereason);
    }

    /**
     * {@inheritDoc}
     */
    public function getClosurereason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClosurereason', []);

        return parent::getClosurereason();
    }

    /**
     * {@inheritDoc}
     */
    public function setClosureexplanation($closureexplanation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClosureexplanation', [$closureexplanation]);

        return parent::setClosureexplanation($closureexplanation);
    }

    /**
     * {@inheritDoc}
     */
    public function getClosureexplanation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClosureexplanation', []);

        return parent::getClosureexplanation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngagement($engagement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngagement', [$engagement]);

        return parent::setEngagement($engagement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngagement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngagement', []);

        return parent::getEngagement();
    }

}
