<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Centroestudios extends \AppBundle\Entity\Centroestudios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'cif', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'cp', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'localidad', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'pais', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'familiaprof', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'subfamiliaprof', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'web', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'rrss', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'centroestudioscol', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'formacion', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'idcategoria', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'categorias', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'imagen'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'cif', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'cp', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'localidad', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'pais', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'familiaprof', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'subfamiliaprof', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'web', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'rrss', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'centroestudioscol', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'formacion', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'idcategoria', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'categorias', '' . "\0" . 'AppBundle\\Entity\\Centroestudios' . "\0" . 'imagen'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Centroestudios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$cp]);

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad($localidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacreacion($fechacreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacreacion', [$fechacreacion]);

        return parent::setFechacreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacreacion', []);

        return parent::getFechacreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaborrado($fechaborrado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaborrado', [$fechaborrado]);

        return parent::setFechaborrado($fechaborrado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaborrado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaborrado', []);

        return parent::getFechaborrado();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFamiliaprof($familiaprof)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFamiliaprof', [$familiaprof]);

        return parent::setFamiliaprof($familiaprof);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamiliaprof()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamiliaprof', []);

        return parent::getFamiliaprof();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubfamiliaprof($subfamiliaprof)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubfamiliaprof', [$subfamiliaprof]);

        return parent::setSubfamiliaprof($subfamiliaprof);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubfamiliaprof()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubfamiliaprof', []);

        return parent::getSubfamiliaprof();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentroestudioscol($centroestudioscol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentroestudioscol', [$centroestudioscol]);

        return parent::setCentroestudioscol($centroestudioscol);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentroestudioscol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentroestudioscol', []);

        return parent::getCentroestudioscol();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\AppBundle\Entity\Usuarios $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormacion(\AppBundle\Entity\Formacion $formacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormacion', [$formacion]);

        return parent::addFormacion($formacion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormacion(\AppBundle\Entity\Formacion $formacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormacion', [$formacion]);

        return parent::removeFormacion($formacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormacion', []);

        return parent::getFormacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcategoria($idcategoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcategoria', [$idcategoria]);

        return parent::setIdcategoria($idcategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcategoria', []);

        return parent::getIdcategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(\AppBundle\Entity\Categorias $id = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setWeb($web)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeb', [$web]);

        return parent::setWeb($web);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeb', []);

        return parent::getWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function addRrss(\AppBundle\Entity\Rrss $rrss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRrss', [$rrss]);

        return parent::addRrss($rrss);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRrss(\AppBundle\Entity\Rrss $rrss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRrss', [$rrss]);

        return parent::removeRrss($rrss);
    }

    /**
     * {@inheritDoc}
     */
    public function getRrss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRrss', []);

        return parent::getRrss();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategoria(\AppBundle\Entity\Categorias $categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategoria', [$categoria]);

        return parent::addCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategoria(\AppBundle\Entity\Categorias $categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategoria', [$categoria]);

        return parent::removeCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorias', []);

        return parent::getCategorias();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif($cif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
