<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Perfilempresa extends \AppBundle\Entity\Perfilempresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'personacontacto', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'cif', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'sector', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'trabajadores', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'cp', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'localidad', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'pais', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'emailcontacto', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'web', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'personaIdpersona', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'horariocontacto', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'fechamodificacion', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'rrss', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'nombreempresa'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'personacontacto', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'cif', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'fechacreacion', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'sector', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'trabajadores', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'cp', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'localidad', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'pais', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'emailcontacto', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'web', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'personaIdpersona', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'horariocontacto', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'fechaborrado', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'fechamodificacion', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'rrss', '' . "\0" . 'AppBundle\\Entity\\Perfilempresa' . "\0" . 'nombreempresa'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Perfilempresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacreacion($fechacreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacreacion', [$fechacreacion]);

        return parent::setFechacreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacreacion', []);

        return parent::getFechacreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setSector($sector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', [$sector]);

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function getSector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', []);

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrabajadores($trabajadores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrabajadores', [$trabajadores]);

        return parent::setTrabajadores($trabajadores);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrabajadores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrabajadores', []);

        return parent::getTrabajadores();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$cp]);

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad($localidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailcontacto($emailcontacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailcontacto', [$emailcontacto]);

        return parent::setEmailcontacto($emailcontacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailcontacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailcontacto', []);

        return parent::getEmailcontacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonaIdpersona($personaIdpersona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonaIdpersona', [$personaIdpersona]);

        return parent::setPersonaIdpersona($personaIdpersona);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonaIdpersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonaIdpersona', []);

        return parent::getPersonaIdpersona();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorariocontacto($horariocontacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorariocontacto', [$horariocontacto]);

        return parent::setHorariocontacto($horariocontacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorariocontacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorariocontacto', []);

        return parent::getHorariocontacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaborrado($fechaborrado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaborrado', [$fechaborrado]);

        return parent::setFechaborrado($fechaborrado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaborrado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaborrado', []);

        return parent::getFechaborrado();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechamodificacion($fechamodificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechamodificacion', [$fechamodificacion]);

        return parent::setFechamodificacion($fechamodificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechamodificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechamodificacion', []);

        return parent::getFechamodificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\AppBundle\Entity\Usuarios $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeb($web)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeb', [$web]);

        return parent::setWeb($web);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeb', []);

        return parent::getWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function addRrss(\AppBundle\Entity\Rrss $rrss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRrss', [$rrss]);

        return parent::addRrss($rrss);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRrss(\AppBundle\Entity\Rrss $rrss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRrss', [$rrss]);

        return parent::removeRrss($rrss);
    }

    /**
     * {@inheritDoc}
     */
    public function getRrss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRrss', []);

        return parent::getRrss();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonacontacto($personacontacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonacontacto', [$personacontacto]);

        return parent::setPersonacontacto($personacontacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonacontacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonacontacto', []);

        return parent::getPersonacontacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreempresa($nombreempresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreempresa', [$nombreempresa]);

        return parent::setNombreempresa($nombreempresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreempresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreempresa', []);

        return parent::getNombreempresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif($cif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

}
